---
- hosts: localhost
  become: yes
  tasks:

  - name: Install some starter packages
    apt:
      name:
        - nginx
        - ufw
        - fail2ban
        - selinux-basics
        - selinux-policy-default
        - auditd
      state: present

  - name: Set UFW logging
    ufw:
      logging: 'on'

  - name: enable UFW service and deny everything
    ufw:
      state: enabled
      policy: deny

  - ufw:
      rule: allow
      name: OpenSSH
  - ufw:
      rule: allow
      port: 80
  - ufw:
      rule: allow
      port: 443

  - name: Copy fail2ban default config
    copy:
      src: /etc/fail2ban/jail.conf
      dest: /etc/fail2ban/jail.local

  - name: Restart fail2ban service
    service:
      name: fail2ban
      state: restarted

  - name: Enable nginx service
    service:
      name: nginx
      enabled: yes

  - name: Enable fail2ban service
    service:
      name: fail2ban
      enabled: yes
